name: Run tests
run-name: ${{ github.actor }} triggered a test run
on: 
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout the repo onto the runner. 
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test --run
      - run: yarn coverage
